### PR TITLE
Add python_requires in setup.py

### PR DESCRIPTION
**Pull request by jamesmyatt**
Ensures that users get the right version of bulwark for their version of python

### CODE REVIEW

**Comment by ZaxR** [comment]
I had purposefully not set a python_requires as specific as the documentation, because it *might* work for not-supported versions, but that's on the user. This will definitely not work for python 2, so at least I should have done `python_requires='>=3'`, though. Thoughts on >=3 vs 3.5?

**Comment by jamesmyatt** [comment]
I think that you need to say the minimum python version so that people know what features and libraries they can use.

Numpy has python_requires of 3.5 or higher https://github.com/numpy/numpy/blob/master/setup.py. I suspect that others like pandas are the same. I'd be very surprised if anyone tries to use this with anything earlier than that.

**Comment by jamesmyatt** [comment]
Also, your CI should back up any setting so if it's >= 3, then you'll need to check it on 3.0, 3.1, etc

**Comment by ZaxR** [comment]
Thanks. v0.5.2 is getting deployed now.

**Pull request merged**
